site_name: fastapi-simple-i18n
site_description: Simple, module-friendly internationalization for FastAPI apps and CLI scripts
repo_url: https://github.com/okelet/fastapi-simple-i18n

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Configuration: configuration.md
  - Usage in FastAPI: fastapi.md
  - Usage in CLI scripts: cli.md
  - Templates: jinja.md
  - Translation files: translation-files.md
  - Extracting translations: extraction.md
  - Modules: modules.md
  - Building the docs: building-docs.md
  - API reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
